/**
 * The agent.py hash this build shipped with.
 *
 * agentBuild.json is generated by scripts/build_agent.py and packaged into the
 * asar. It is absent in a checkout that never built the agent, and absent means
 * "no opinion" — there is nothing to compare a running agent against.
 */

"use strict";

const { IS_DEV } = require("./constants");

let _expected;

/** @returns {string|null} */
function expectedAgentSource() {
  if (_expected === undefined) {
    try {
      _expected = require("./agentBuild.json").source_sha || null;
    } catch {
      _expected = null;
    }
  }
  return _expected;
}

/**
 * Whether a running agent was built from the source this app shipped with.
 * A mismatch means the binary was swapped or predates the app, so nothing it
 * reports can be trusted.
 *
 * @param {unknown} reported - source_sha from the agent's status payload
 * @param {string|null} [expected] - test seam
 * @returns {boolean}
 */
function agentSourceMatches(reported, expected = expectedAgentSource()) {
  if (IS_DEV || !expected) {
    return true;
  }
  return typeof reported === "string" && reported === expected;
}

module.exports = { expectedAgentSource, agentSourceMatches };
