#!/usr/bin/env node
/**
 * Removes build output. These are gitignored and regenerated by build:agent /
 * electron-builder, but they accumulate a stale installer per release and are
 * the bulk of the working tree on disk.
 *
 * Usage: node scripts/clean.js [--dry-run]
 */

"use strict";

const fs = require("fs");
const path = require("path");

const TARGETS = ["release", "dist", "build_tmp", "resources/agent.exe", "resources/agent"];

const ROOT = path.join(__dirname, "..");
const dryRun = process.argv.includes("--dry-run");

function sizeOf(target) {
  let total = 0;
  const stack = [target];
  while (stack.length > 0) {
    const current = stack.pop();
    const stat = fs.lstatSync(current);
    if (stat.isDirectory()) {
      for (const entry of fs.readdirSync(current)) {
        stack.push(path.join(current, entry));
      }
    } else {
      total += stat.size;
    }
  }
  return total;
}

function format(bytes) {
  if (bytes >= 1024 ** 3) {
    return `${(bytes / 1024 ** 3).toFixed(1)} GB`;
  }
  if (bytes >= 1024 ** 2) {
    return `${(bytes / 1024 ** 2).toFixed(0)} MB`;
  }
  return `${(bytes / 1024).toFixed(0)} KB`;
}

let freed = 0;
for (const target of TARGETS) {
  const full = path.join(ROOT, target);
  if (!fs.existsSync(full)) {
    continue;
  }
  const bytes = sizeOf(full);
  freed += bytes;
  console.log(`${dryRun ? "would remove" : "removing"}  ${target}  (${format(bytes)})`);
  if (!dryRun) {
    fs.rmSync(full, { recursive: true, force: true });
  }
}

if (freed === 0) {
  console.log("Nothing to clean.");
} else {
  console.log(`\n${dryRun ? "Would free" : "Freed"} ${format(freed)}.`);
  if (!dryRun) {
    console.log("Run `pnpm run build:agent` before packaging again.");
  }
}
