"use strict";

/**
 * Regenerates assets/css/fonts.css and assets/fonts/ from Google's Fonts
 * CSS2 API. Run with `node scripts/fetch-fonts.js` from the repo root.
 *
 * Every non-Inter family is renamed to the shared CSS font-family "Noto
 * Sans" so the browser selects the right script's glyphs per character via
 * unicode-range, matching the fallback stack in assets/css/i18n.css
 * (`Inter, "Noto Sans", ...`) — no per-locale font-family switching needed.
 *
 * Edit FAMILIES below to add a script or change weights, then re-run.
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const FAMILIES = [
  ["inter", "Inter:wght@400;500;600;700;800"],
  ["noto-sans-devanagari", "Noto+Sans+Devanagari:wght@400;500;600;700;800"],
  ["noto-sans-bengali", "Noto+Sans+Bengali:wght@400;500;600;700;800"],
  ["noto-sans-tamil", "Noto+Sans+Tamil:wght@400;500;600;700;800"],
  ["noto-sans-telugu", "Noto+Sans+Telugu:wght@400;500;600;700;800"],
  ["noto-sans-kannada", "Noto+Sans+Kannada:wght@400;500;600;700;800"],
  ["noto-sans-malayalam", "Noto+Sans+Malayalam:wght@400;500;600;700;800"],
  ["noto-sans-arabic", "Noto+Sans+Arabic:wght@400;500;600;700;800"],
  ["noto-sans-jp", "Noto+Sans+JP:wght@400;700"],
  ["noto-sans-kr", "Noto+Sans+KR:wght@400;700"],
];

async function fetchText(url, extraHeaders) {
  const res = await fetch(url, { headers: { "User-Agent": UA, ...extraHeaders } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.text();
}

async function fetchBuffer(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

async function main() {
  let combined =
    "/* Self-hosted fonts. Generated by scripts/fetch-fonts.js from Google Fonts' CSS2 API. Do not hand-edit — regenerate instead. */\n";
  let totalBytes = 0;
  let totalFiles = 0;

  for (const [slug, spec] of FAMILIES) {
    const dir = path.join(ROOT, "assets/fonts", slug);
    fs.rmSync(dir, { recursive: true, force: true });
    fs.mkdirSync(dir, { recursive: true });

    const css = await fetchText(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`, {
      Accept: "text/css",
    });

    const blocks = css.match(/@font-face\s*\{[^}]*\}/g) || [];
    let familyCss = `\n/* ${slug} */\n`;
    let i = 0;
    for (const block of blocks) {
      const urlMatch = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/);
      if (!urlMatch) continue;
      const url = urlMatch[1];
      const weightMatch = block.match(/font-weight:\s*(\d+)/);
      const weight = weightMatch ? weightMatch[1] : "400";
      i++;
      const fname = `${weight}-${i}.woff2`;
      const buf = await fetchBuffer(url);
      fs.writeFileSync(path.join(dir, fname), buf);
      totalBytes += buf.length;
      totalFiles++;

      let localBlock = block.replace(url, `../fonts/${slug}/${fname}`);
      if (slug !== "inter") {
        localBlock = localBlock.replace(/font-family: '[^']*';/, "font-family: 'Noto Sans';");
      }
      familyCss += localBlock + "\n";
    }
    combined += familyCss;
    console.log(`${slug}: ${blocks.length} blocks fetched`);
  }

  fs.writeFileSync(path.join(ROOT, "assets/css/fonts.css"), combined);
  console.log(`DONE. ${totalFiles} files, ${(totalBytes / 1024 / 1024).toFixed(2)} MB total`);
}

main().catch((err) => {
  console.error("FAILED:", err);
  process.exit(1);
});
